### PR TITLE
Add containerized dev option

### PR DESCRIPTION
**Pull request by NickBorgers**
This is how I developed the changes in #21 without installing any of the project's dependencies on my machine.

### CODE REVIEW

**Comment by NickBorgers** [comment]
If you have any interest in this I'll add some basic docs for usage.

**Comment by Drafteed** [comment]
I'm not sure about this. To install a project without installing dependencies on your host machine, you can use venv.

**Comment by bieniu** [comment]
I think it makes more sense to add support for devcontainer. Like here https://github.com/home-assistant-libs/aioshelly/tree/main/.devcontainer

**Comment by NickBorgers** [comment]
Up until right this moment I thought [the Dev Container thing](https://aka.ms/devcontainer.json) was VSCode-specific. I'm happy to flip this PR to adopt that approach instead. This will also enable me to revisit the conversation at work; though there I'll need to be more careful about which IDEs are popular and which support devcontainers. The pair of bridges I hadn't been able to cross there were allowing someone who didn't use VSCode to quickly jump in just as easily and making it play nice with some in-house environmental tooling.

> I'm not sure about this. To install a project without installing dependencies on your host machine, you can use venv.

The containerized approach serves me when I write in any language, and I jump around quite a bit.

**Comment by NickBorgers** [comment]
Hmm, looking only slightly closer [Development Containers are a Microsoft-branded specification (scroll down all th way to bottom right corner)](https://containers.dev/), thus their adoption in VSCode and GitHub.

I do like the experience, but please let me know if that's a turnoff for you.

**Pull request closed without merging**
